AI_PHOTO_PROMPTS = {

    "surfing": {
        "title": "Сёрф",

        "male": {
            "title": "Мужские",

            "walk_with_board": {
                "title": "С доской идет",
                "prompt": """Man from the attached photo walking dynamically along a wooden deck at a beach surf shack, captured in a closer, portrait-style framing to clearly preserve his face. Medium-close shot from mid-torso up, the camera slightly in front of him as he walks toward it, looking directly into the lens with a calm, confident expression so all facial features are sharp and recognizable. He carries a white surfboard diagonally across his body, one hand gripping the rail while the board rests against his shoulder and chest. He wears a relaxed white linen shirt with the top buttons casually open and sleeves rolled to the forearms, warm golden sunlight sculpting his face and collarbones.
Background: rustic wooden beach cabins and palm plants softly blurred behind him along the boardwalk, hints of long shadows on the planks. Style: ultra-realistic vintage film photography aesthetic in 4K, warm golden-hour tones, natural contrast, subtle film grain and a light vignette. Camera language: static eye-level medium-close shot on a 50 mm lens with shallow depth of field, tack-sharp focus on his eyes, face and upper torso while the surfboard edge and background fall slightly out of focus. Atmosphere: intimate, confident surf-lifestyle mood, like a hero portrait taken moments before heading to the water. Preserve the man’s facial features, proportions, hairstyle and identity from the attached photo as accurately as possible, with no distortion."""
            },

            "surfing": {
                "title": "Серфит",
                "prompt": """A man from the attached photo is depicted riding a wave on a surfboard in a dynamic low-angle action shot. He is crouching on the board exactly like in the reference: balanced, knees bent, one hand extended forward for control, the other close to his body. His torso is angled forward, expression focused yet joyful. The environment features bright natural daylight, a clear pale-blue sky, and clean turquoise ocean water with small splashes and foam around the board. The wave beneath him is smooth, creating a sense of motion and speed. The surfboard is white with subtle reflections from the sun. Style: ultra-realistic 4K action photography with crisp details and fast shutter clarity. Lighting: strong natural sunlight from above-right, creating soft highlights on his shoulders, arms and facial features. Camera placed very low near the surface of the wave, looking slightly upward, giving a powerful dynamic perspective. Shot resembles a 70–135 mm telephoto action lens with high clarity and shallow-to-medium depth of field. Details: water droplets frozen in motion, salty texture on the skin, realistic wet hair, shadows along muscles, sun reflections on the board and water. Atmosphere: energetic, fresh, athletic, lively ocean vibe. Preserve the face, identity, proportions and expression from the attached photo exactly."""
            },

            "yacht": {
                "title": "На яхте",
                "prompt": """A man is depicted in a waist-up dynamic pose on a sailing yacht, with his upper body leaning outward over the ocean. His torso faces the camera directly, shoulders open, and he extends one arm outward to the side for balance, while the other arm lightly holds or hovers near the yacht’s ropes. His posture is relaxed but athletic, and he looks straight into the camera with a confident, natural expression. His face is positioned close enough for clear detail and accurate identity transfer.
He wears bright swim shorts and a cap; his torso is bare and sunlit. The shot is framed from the waist up, but the setting clearly reads as a yacht: visible railing, ropes, mast lines and part of the deck framing the right side of the image. The horizon and deep blue ocean appear in the background, with a bright summer sky overhead.
Style: ultra-realistic 4K outdoor portrait-action hybrid. Lighting: strong natural midday sun from above-right, producing crisp highlights on his chest, arms and face, with clean shadows for definition. Camera angle is slightly low and close, enhancing presence and detail. Lens feel: 50–85 mm portrait-action focal length with shallow-to-medium depth of field, keeping the background recognizable but softly separated.
Details: natural skin texture, subtle sheen from sunlight, realistic facial definition, slight wind movement in the ropes and hair, light reflections on the yacht metal and ocean surface. Atmosphere: adventurous, bright, energetic, summer freedom.
Replace the character’s face with the face from the attached portrait photo, preserving identity, proportions and natural anatomy. Avoid distortions; ensure clean photorealistic integration."""
            },

            "board_on_head": {
                "title": "С доской на голове",
                "prompt": """Black and white medium shot portrait of the man from the attached photo holding a white surfboard horizontally behind his head, framing his face. He is wearing a loose button-up shirt with sleeves rolled up. Shot on Kodak Tri-X 400 black and white film, 35mm lens, f/2.8 aperture. High contrast, film grain, natural light casting deep shadows under the surfboard. The ocean horizon is blurred in the background. Serious, confident gaze directly at the camera. Monochrome aesthetic, vintage surf photography style. Seamlessly integrate the face, hairstyle, and physical features from the reference image."""
            },

            "in_water": {
                "title": "На доске в море",
                "prompt": """The man from the attached photo is depicted partially submerged in calm ocean water during golden hour, with his torso in the water while he leans forward onto a surfboard. His chest, forearms and fists rest on the board for support, and his head is turned toward the camera, making direct eye contact.
The scene matches the reference: warm golden-hour sunlight, a glowing orange–peach sky, soft haze over the horizon, and reflective water shimmering like molten gold. The surfboard is long with cool blue tones, floating stably beneath him.
Style: ultra-realistic 4K cinematic photography with soft bokeh and natural film-like color grading. Lighting: low sunset light from the left, creating warm rim-light along his shoulders, hair and jawline. Camera is placed extremely low, almost touching the water surface, medium-long shot with an 85–135 mm optical look and shallow depth of field.
Details: wet skin texture, water droplets on his arms, natural highlights, gentle ripples around his torso, smooth gradients in the sky. Atmosphere: calm, warm, intimate, serene.
Preserve the face, identity, proportions and expression from the attached photo exactly"""
            },
        },

        "female": {
            "title": "Женские",

            "walk_with_board": {
                "title": "С доской идет",
                "prompt": """Young woman from the attached photo walking dynamically along a wooden deck at a beach surf shack, captured in a closer, portrait-style framing to clearly preserve her face. Medium-close shot from mid-torso up, the camera slightly in front of her as she walks toward it, looking directly into the lens with a calm, confident expression so all facial features are sharp and recognizable. She carries a white surfboard diagonally across her body, one hand gripping the rail while the board rests against her shoulder and chest. She wears a relaxed white linen shirt with the top buttons casually open and sleeves rolled to the forearms, warm golden sunlight sculpting her face, collarbones and fabric folds.
Background: rustic wooden beach cabins and palm plants softly blurred behind her along the boardwalk, with hints of long shadows on the planks. Style: ultra-realistic vintage film photography aesthetic in 4K, warm golden-hour tones, natural contrast, subtle film grain and a light vignette. Camera language: static eye-level medium-close shot on a 50 mm lens with shallow depth of field, tack-sharp focus on her eyes, face and upper torso while the surfboard edge and background fall slightly out of focus. Atmosphere: confident, effortlessly cool surf-lifestyle mood, like a hero portrait taken moments before she heads to the water. Preserve the woman’s facial features, proportions, hairstyle and identity from the reference face as accurately as possible, with no distortion."""
            },

            "surfing": {
                "title": "Серфит",
                "prompt": """A woman is depicted riding a wave on a surfboard in a dynamic low-angle action shot. She is crouching exactly like in the reference: knees bent, balanced, one hand extended forward for control and the other close to her body. Her torso leans slightly forward in an athletic surfing stance, and she looks fully focused and energized. She wears a bikini top and short swimming-style surf shorts.
The environment matches the original exposure: bright natural daylight, a clear pale-blue sky and clean turquoise ocean water with splashes and foam around the board. The wave beneath her is smooth and creates a strong sense of motion and speed. The surfboard is white with sun reflections.
Style: ultra-realistic 4K action photography with crisp detail and fast shutter clarity. Lighting: strong natural sunlight from above-right, casting soft highlights across her shoulders, arms, legs and facial features. The camera is positioned very low near the water surface, angled slightly upward for a dynamic perspective. The shot resembles a 70–135 mm telephoto action lens with medium depth of field.
Details: realistic wet hair, water droplets frozen mid-air, natural skin texture, subtle sun highlights, sharp reflections on the board and wave surface. Atmosphere: energetic, fresh, athletic, full of ocean movement.
Generate a natural, realistic female face with balanced proportions and clean anatomy, maintaining consistent photorealism. Avoid distortions"""
            },

            "yacht": {
                "title": "На яхте",
                "prompt": """A woman is depicted in a dynamic waist-up pose on a sailing yacht, with her upper body leaning slightly outward over the ocean in a relaxed, confident manner. Her torso faces the camera directly, shoulders open, and one arm extends outward to the side for balance while the other lightly touches or hovers near the yacht’s ropes. She looks straight into the camera with a natural, expressive, photorealistic face.
She is wearing a lightweight white shirt, unbuttoned at the top and bottom for an airy summer look, and bikini bottoms. The shirt moves gently with the breeze, creating soft flowing folds, while her skin catches warm sunlight. Her posture remains athletic but feminine, matching the energy of the scene.
The setting: clearly a yacht, with visible railing, ropes, mast lines and part of the deck framing the right side. Behind her, the deep blue ocean and bright sky create a clean, sunlit backdrop.
Style: ultra-realistic 4K outdoor portrait-action hybrid with cinematic clarity. Lighting: strong natural midday sunlight from above-right, producing crisp highlights across her face, chest and arms, with clean, flattering shadows for depth. Camera is positioned slightly low and close, capturing detailed facial features while still showing the yacht environment. Lens feel: 50–85 mm portrait lens with shallow-to-medium depth of field, keeping her sharp and the background softly separated but recognizable.
Details: natural skin texture, subtle sun glow, gentle wind movement in her shirt and hair, realistic reflections on the yacht metal and water surface. Atmosphere: bright, warm, adventurous, summery.
Replace the character’s face with the face from the attached portrait photo, preserving identity, proportions and natural anatomy. Avoid distortions and maintain full photorealism."""
            },

            "hide_behind_board": {
                "title": "За доской прячется",
                "prompt": """Young woman standing on a sandy beach, leaning slightly against a tall turquoise surfboard that hides half of her body and covers one side of her face. The camera is framed in a vertical medium shot from thighs up, straight-on at eye level, so her visible eye and facial features are clear and recognizable. She wears a sleek black wetsuit that fits closely to her body, with wet, tousled hair falling around her face, giving a natural, effortless surf-girl look. One hand holds the edge of the surfboard near the center, fingers relaxed but firm.
Background: soft, hazy coastline with pale sand dunes and a muted pastel sky filled with light clouds; no crowds, only minimal horizon details to keep focus on her and the board. Style: ultra-realistic editorial surf portrait in 4K, slightly warm, sun-bleached color palette with subtle film grain and gentle contrast, like a vintage fashion magazine spread. Lighting: late afternoon or early morning soft sunlight, diffused and warm, with smooth shadows on her face and wetsuit, no harsh highlights. Camera language: static, slightly off-center composition with the surfboard occupying one side of the frame and her face aligned near the vertical third, shallow depth of field keeping her and the board sharp while the background softly blurs. Mood and atmosphere: calm, introspective, slightly melancholic summer mood — a quiet moment before or after a surf session. Preserve the woman’s facial features, proportions, hairstyle and identity from the reference face as accurately as possible, with no distortion."""
            },

            "in_water": {
                "title": "На доске в море",
                "prompt": """A woman is depicted partially submerged in calm ocean water during golden hour, with her torso in the water while she leans forward onto a surfboard. She wears a swimsuit, and her chest, forearms and fists rest on the board for support. Her head is turned toward the camera, making direct eye contact with a natural, harmonious female facial structure.
The environment matches the reference: warm golden-hour sunlight, a glowing orange–peach sky with soft haze near the horizon, and reflective water shimmering like molten gold. The surfboard is long and cool blue-toned, floating steadily beneath her.
Style: ultra-realistic 4K cinematic photography with soft bokeh and gentle film-like grading. Lighting: low sunset light from the left, creating warm rim-light along her shoulders, hair and jawline. Camera positioned extremely low, nearly at the water surface, medium-long shot with an 85–135 mm optical look and shallow depth of field.
Details: wet skin texture, water droplets on her arms and collarbones, subtle ripples around her torso, soft reflections on the water surface, smooth warm gradients in the sky. Atmosphere: calm, intimate, warm and serene.
Generate a natural, realistic female face with clean proportions and correct anatomy; avoid distortions and maintain consistent photorealism"""
            },
        },
    },

    "animals": {
        "title": "Животные",

        "male": {
            "title": "Мужские",

            "dalmatians": {
                "title": "Долматинцы",
                "prompt": """realistic cinematic medium close-up street-fashion portrait of a young adult man depicted with the face from the attached reference photo, identity fully preserved (features, proportions, bone structure, skin texture, lighting continuity); the man sits on a stone curb, leaning slightly forward with his chin resting on his hand, calm thoughtful expression; wearing an oversized dark blazer, oversized soft cotton T-shirt, and wide loose-fit trousers, white crew socks, black leather loafers. background: European stone wall and cobblestone street (kept soft and compressed due to close portrait crop). Two dalmatian dogs positioned tightly next to the man, one slightly behind shoulder level and one closer to the curb, both elegant, calm, looking toward the camera; dogs remain fully visible within the portrait crop. Lighting: soft ambient daylight, neutral-warm, subtle reflected fill from stone surfaces; shallow-to-medium depth of field with sharper focus on the man’s face and front dog; vertical 9:16 framing with tighter composition, face centered slightly above mid-frame; ≈50–70 mm portrait lens feel; gentle film grain, natural color grade; palette #d9cdb8 #1e1e1e #7f2c2c #2b2f3a #e9c9b3 #2e3f20. Face Integration: seamless insertion of the user’s face from the reference, zero distortion, no beautification, identity preserved, lighting matched, edges and shadows blended naturally. –ar 9:16 –stylize 100 –quality 1 –seed 42157 –no text, logos, watermarks, distortions, duplicates, blur, artifacts, color fringing, anatomy errors"""
            },

            "retrievers": {
                "title": "Ретриверы",
                "prompt": """Young man in the scene is depicted with the exact face from the attached reference photo, keeping all facial features, proportions and natural skin texture. No changes, no beautification, no reinterpretation – identity must match perfectly. He is lying on green grass. Around him, 7–9 small golden retriever puppies rest on his shoulders, chest and around his head.Top-down overhead shot, medium close-up MCU. Camera ≈40–55 mm, focus locked on his face; puppies in the near foreground slightly softer.Lighting is natural outdoor daylight, soft and warm, coming from roughly the 10–11 o’clock direction.Textures visible: soft puppy fur, grassy surface, knitted fabric of his sweater.Warm color grade, mild contrast, slightly increased saturation. Cozy, joyful mood.High-quality realistic color photograph. No flash, no effects, no identity drift. --ar 2:3 --stylize 100 --quality 1 --seed 348921--no text, logos, watermarks, blur, artifacts, extra limbs, face alteration, smoothing, reshaping, beautification. Face Integration: seamlessly merge the man’s face from the reference photo, maintaining true identity, lighting direction, micro-details, no beautification, no distortion. –ar 4:5 –stylize 100 –seed 42157 –quality 1–no text, logos, watermarks, distortions, blur, duplicates, artifacts, color fringing, anatomy errors, extra limbs"""
            },

            "marmot": {
                "title": "Бобр курва",
                "prompt": """realistic color photograph of a slim young adult man seated at a small round metal cafe table, front-right 3/4 angle, holding a folded newspaper on the table; he is looking directly at the camera with a calm, focused expression. he is depicted with the face from the attached reference photo of the user, preserving all facial features, proportions, bone structure, natural skin texture and true skin tone, no beautification or reshaping. classic dark sunglasses of a standard rectangular shape, beige oversized blazer, beige wide-leg trousers, light neutral top underneath. vintage French-style cafe veranda with red-burgundy wall panels and gold window lettering behind him; white porcelain cup and saucer on the table, warm cozy atmosphere. soft ambient daylight coming from the left, gentle shadows, shallow–medium depth of field, normal ≈50 mm camera look, subtle film grain and light vignette, warm slightly contrasty vintage grade in the palette #7b2b2b #c9a24d #1e1e1e #8a5a45 #e6b9a3. place a small marmot sitting on the man’s lap instead of on the table; its body leaning against his torso, front paws gently holding onto his forearm, like in the reference image, both the man and the marmot looking toward the camera; realistic proportions, detailed fur, paws resting on the tabletop, lighting and shadows fully matched to the environment. keep the original environment, lighting and camera composition unchanged, only change the subject’s gender, outfit and face identity to match the attached reference. no text, logos, watermarks, distortions, bad anatomy, extra limbs, duplicates, blur, compression artifacts."""
            },

            "big_retriever": {
                "title": "Биг ретривер",
                "prompt": """Bro from the attached photo is depicted in a realistic color selfie portrait together with a large Labrador Retriever dog. Their heads are very close, cheek to cheek, the dog has its tongue out and is looking at the camera. Shot outdoors, with a bright blurred background like clouds, sky or water. Lighting is soft, diffused daytime light on an overcast day, with no harsh shadows. Camera – close-up, frontal eye-level angle, selfie with a wide-angle 24–28 mm lens, tight centered framing, focus on the faces. The man wears t-shirt, has wet hair, the dog has short smooth fur, with detailed textures of skin, fur, tongue and teeth. The atmosphere is light and joyful, with the feel of a live documentary moment. Preserve the man’s face, expression and proportions from the attached photo without distortion, with a natural neutral-cool color. --ar 4:5 --stylize 100 --seed 42719 --quality 1 --no text, logos, watermarks, distorted shapes, duplicates, blur, low quality, artifacts, color fringing, anatomy errors, extra limbs"""
            },

            "horse": {
                "title": "Лошадь",
                "prompt": """Young adult man is depicted with the face from my uploaded reference photo, preserving all facial features, proportions, natural skin texture and true tone. He is leaning against a light gray street pole positioned on the right side of the frame, resting his right shoulder against it. His body is tilted backward–left at approximately a 30-degree angle. Outfit: dark brown knitted sweater (slightly loose fit), wide gray trousers with soft drape and clean straight silhouette. Expression calm, confident; gaze directed at the camera.
Exposure / Composition: In the left area of the frame, in the open negative space, the head of a white horse is visible; it looks directly into the camera. The rest of the horse’s body remains behind the man, partially obscured by his figure. The vertical pole forms the right framing anchor; the horse’s head forms the left visual mass. Focus is on the man’s face; the horse is clear but in the secondary plane.
Environment: European city street, beige stone facades, red cafe awnings, outdoor chairs, zebra crossing. Lighting: soft natural daylight; key light from the front-left (≈10 o’clock), gentle ambient fill; no flash. Camera: medium close-up (MCU), eye-level, short-telephoto ≈85 mm, shallow depth of field ≈f/2.0; vertical framing, pole as a dominant line, subject slightly right of center, one-point perspective.
Details & Textures: knit sweater texture, soft wool-blend trousers, concrete/asphalt, matte metal pole, horse coat texture. Color grade: soft contrast, neutral–slightly warm palette (#F2F2F2 #565A5F #7A7E83 #D6C6B1 #C22B2B #D8A88A). Post-process: light bokeh, clean realism, no grain, artifacts or distortions.
-ar 9:16 --stylize 100 --quality 1 --no text, watermarks, blur, distortions, anatomy errors, duplicates, extra limbs"""
            },
        },

        "female": {
            "title": "Женские",

            "dalmatians": {
                "title": "Далматинцы",
                "prompt": """realistic cinematic medium close-up street-fashion portrait of a young woman depicted with the face from the attached reference photo, identity preserved perfectly (features, proportions, bone structure, micro-texture, lighting continuity); the woman sits on a stone curb, leaning slightly forward with his chin resting on her hand, calm thoughtful expression; wearing dark blazer, short tweed-like skirt, white crew socks, black leather loafers with metal bit, dark-red leather shoulder bag with chain strap; background: European stone wall and cobblestone street (kept soft and compressed due to close portrait crop). Two dalmatian dogs positioned tightly next to the woman, one slightly behind shoulder level and one closer to the curb, both elegant, calm, looking toward the camera; dogs remain fully visible within the portrait crop. Lighting: soft ambient daylight, neutral-warm, subtle reflected fill from stone surfaces; shallow-to-medium depth of field with sharper focus on the woman’s face and front dog; vertical 9:16 framing with tighter composition, face centered slightly above mid-frame; ≈50–70 mm portrait lens feel; gentle film grain, natural color grade; palette #d9cdb8 #1e1e1e #7f2c2c #2b2f3a #e9c9b3 #2e3f20. Face Integration: seamless insertion of the user’s face from the reference, zero distortion, no beautification, identity preserved, lighting matched, edges and shadows blended naturally. –ar 9:16 –stylize 100 –quality 1 –seed 42157 –no text, logos, watermarks, distortions, duplicates, blur, artifacts, color fringing, anatomy errors"""
            },

            "retrievers": {
                "title": "Ретриверы",
                "prompt": """Young woman in the scene is depicted with the exact face from the attached reference photo, keeping all facial features, proportions and natural skin texture. No changes, no beautification, no reinterpretation – identity must match perfectly. She is lying on green grass. Around her, 7–9 small golden retriever puppies rest on her shoulders, chest and around his head.Top-down overhead shot, medium close-up MCU. Camera ≈40–55 mm, focus locked on his face; puppies in the near foreground slightly softer.Lighting is natural outdoor daylight, soft and warm, coming from roughly the 10–11 o’clock direction.Textures visible: soft puppy fur, grassy surface, knitted fabric of his sweater.Warm color grade, mild contrast, slightly increased saturation. Cozy, joyful mood.High-quality realistic color photograph. No flash, no effects, no identity drift. --ar 2:3 --stylize 100 --quality 1 --seed 348921--no text, logos, watermarks, blur, artifacts, extra limbs, face alteration, smoothing, reshaping, beautification. Face Integration: seamlessly merge the man’s face from the reference photo, maintaining true identity, lighting direction, micro-details, no beautification, no distortion. –ar 4:5 –stylize 100 –seed 42157 –quality 1–no text, logos, watermarks, distortions, blur, duplicates, artifacts, color fringing, anatomy errors, extra limbs"""
            },

            "marmot": {
                "title": "Бобр курва",
                "prompt": """realistic color photograph of a slim adult woman seated at a small round metal cafe table, front-right 3/4 angle, holding a folded newspaper on the table; she is looking directly at the camera with a calm, focused expression. she is depicted with the face from the attached reference photo of the user, preserving all facial features, proportions, bone structure, natural skin texture and true skin tone, no beautification or reshaping. short wavy brown hair to the shoulders, black beret, cat-eye glasses, black ribbed turtleneck, patterned midi skirt. vintage French-style cafe veranda with red-burgundy wall panels and gold window lettering behind her; white porcelain cup and saucer on the table, warm cozy atmosphere. soft ambient daylight coming from the left, gentle shadows, shallow–medium depth of field, normal ≈50 mm camera look, subtle film grain and light vignette, warm slightly contrasty vintage grade in the palette #7b2b2b #c9a24d #1e1e1e #8a5a45 #e6b9a3. place a small marmot sitting on the woman’s lap instead of on the table; its body leaning against her torso, front paws gently holding onto her forearm, the marmot looking at езру camera; realistic proportions, detailed fur, whiskers and paws, lighting and shadows fully matched to the environment. keep the original environment, outfit, lighting and camera composition unchanged, only change the face identity to match the attached reference. no text, logos, watermarks, distortions, bad anatomy, extra limbs, duplicates, blur, compression artifacts."""
            },

            "big_retriever": {
                "title": "Биг ретривер",
                "prompt": """Girl from the attached photo is depicted in a realistic color selfie portrait together with a large Labrador Retriever dog. Their heads are very close, cheek to cheek, the dog has its tongue out and is looking at the camera. Shot outdoors, with a bright blurred background like clouds, sky or water. Lighting is soft, diffused daytime light on an overcast day, with no harsh shadows. Camera – close-up, frontal eye-level angle, selfie with a wide-angle 24–28 mm lens, tight centered framing, focus on the faces. The girl has wet hair, the dog has short smooth fur, with detailed textures of skin, fur, tongue and teeth. The atmosphere is light and joyful, with the feel of a live documentary moment. Preserve the girl’s face, expression and proportions from the attached photo without distortion, with a natural neutral-cool color. --ar 4:5 --stylize 100 --seed 42719 --quality 1 --no text, logos, watermarks, distorted shapes, duplicates, blur, low quality, artifacts, color fringing, anatomy errors, extra limbs"""
            },

            "horse": {
                "title": "Лошадь",
                "prompt": """Young woman is depicted with the face from my uploaded reference photo, preserving all facial features, proportions, natural skin texture and true tone. She is leaning against a light gray street pole positioned on the right side of the frame, resting her right shoulder against it. Her body is tilted backward–left at approximately a 30-degree angle. Outfit: white ribbed crop top, gray oversized blazer, pleated gray skirt with a gold V-shaped buckle. Expression calm and confident; gaze directed at the camera.
Exposure / Composition: In the left area of the frame, in the open negative space, the head of a white horse is visible; it is turned toward the camera and looks directly into the lens. The rest of the horse’s body is in the right area of the frame behind the woman and partly obscured by her figure. The vertical pole forms the right framing anchor; the horse’s head forms the left visual mass. Focus is on the woman’s face; the horse remains sharp but in the secondary plane.
Environment: European city street, beige stone facades, red cafe awnings, outdoor chairs, zebra crossin"""
            },
        },
    },

    "winter": {
        "title": "Зима",

        "male": {
            "title": "Мужские",

            "floor": {
                "title": "На полу",
                "prompt": """Person from the attached photo depicted lying on a dark party floor after a wild night, surrounded by a thick layer of bright metallic confetti, glitter and tinsel. He wears an elegant black suit with a white dress shirt unbuttoned at the top, dark sunglasses, a festive tinsel garland draped around his neck and shoulders, a party blower in his mouth, relaxed pose with a slightly confident, amused expression. Above him, in the upper part of the frame, only the legs of party guests are visible: on the left a man in tailored light grey dress trousers and polished black leather shoes, on the right a woman in a short black cocktail dress, sheer black tights and high-heel sandals, their legs framing the person lying on the floor. Environment: dark club floor completely covered with gold, silver, blue, red, green and purple confetti pieces, shiny foil streamers and serpentine, with deep black drapery in the background, creating a nightclub afterparty chaos feeling. Photo-realistic, cinematic 4K fashion editorial style, high contrast, deep shadows, strong emphasis on the sparkle of confetti and tinsel, luxurious and stylish look. Lighting: warm directional studio light from above and slightly from the side, soft but defined shadows, glossy highlights on skin, shoes and suit, background fading into darkness. Camera language: high angle almost top-down medium shot on a professional full-frame camera with a 50–85 mm lens, moderately shallow depth of field, crisp focus on the subject’s face and upper body, rich confetti details across the frame. Mood and atmosphere: ironic, bold, expensive post-party glamour. Preserve the face, proportions and expression from the attached photo without distortion."""
            },

            "chair_mountain": {
                "title": "Стул на горе",
                "prompt": """Young man from the attached photo sitting on a wooden chair in the middle of a sunny snowy mountain landscape. He wears a chunky knitted winter sweater with a Nordic pattern: red and white design across the chest and sleeves, red collar, red cuffs and hem, white sleeves and base, with a thin white layer of clothing visible at the neck. On the lower body he has black ski or trekking pants. He sits leaning slightly forward, elbows resting on his thighs, hands loosely clasped in front of him with relaxed fingers. The man has the same facial features, hairstyle and overall appearance as in the attached photo, preserved accurately without distortion or stylization, with a calm, confident gaze directly into the camera. Background: bright open snowfield under clear daylight, with a large snow-covered mountain softly blurred behind him and a clean pale blue winter sky above. Style: photo-realistic, clean cinematic outdoor portrait in 4K, with a cool snowy color palette and warm skin and sweater tones, subtle backlight along the hair and shoulders. Lighting: bright daytime mountain sun, gentle natural shadows on the face, reflected light from the snow below creating even, flattering illumination on the skin and sweater texture. Camera language: static frontal or slightly low angle, medium to medium-close shot (from chest to knees), professional full-frame camera with a 50–85 mm lens, moderately shallow depth of field, sharp focus on the face and hands, mountains and snow in the background softly blurred. Mood and atmosphere: fresh winter day in the mountains, feeling of freedom, calm and cozy warmth thanks to the sweater. Preserve the face, proportions, facial expression and all appearance details from the attached photo as accurately as possible, with no distortion."""
            },

            "frozen_face": {
                "title": "Ебало замерзшее",
                "prompt": """Young man from the attached photo shown in an extreme close-up winter portrait, his face filling the frame from mid-forehead to chin, directly facing the camera. Only his face is visible, tightly framed by a fur-lined hood and thick frost. His skin has a cold rosy tone, long dark lashes for a man and well-defined brows, with subtle skin texture visible on the cheeks and nose. His nose, cheeks and the area around his mouth are covered in dense frost and tiny ice crystals, as if he has been walking in severe sub-zero temperatures; a thin layer of frost also sits on his natural pinkish lips. Around his face, the fur trim of the hood and a high winter collar are heavily coated with snow and rime, with a few frozen strands of hair peeking out, also covered in ice. The background is softly blurred and indistinct in cold blue tones, so all attention is drawn to his eyes. Style: hyper-realistic cinematic winter portrait in 4K, with micro-details in skin, frost and fur, a cool blue-cyan color palette contrasted by gentle warm tones in the lips and cheeks. Lighting: soft diffused northern daylight, like an overcast snowy day, with no harsh shadows, evenly illuminating the face and emphasizing the depth of his eyes and the texture of the frost, slightly cool in tone. Camera language: static frontal extreme close-up shot with an 85–100 mm lens and very shallow depth of field, razor-sharp focus on the eyes and center of the face, fur and background gently blurred. Mood and atmosphere: intense arctic cold, quiet, resilience and inner strength, his gaze steady, focused and slightly contemplative. Preserve the male face, proportions, gaze and all appearance details from the attached photo as accurately as possible, with no distortion"""
            },

            "soviet": {
                "title": "Совок",
                "prompt": """Young man from the attached photo standing outdoors in a snowy courtyard in front of a Soviet-era apartment block, captured in a closer portrait framing. The camera is focused tightly on him from mid-chest upward, so his face and features are clearly visible and sharp, while the background buildings, trees, streetlights and basketball hoop are softly blurred. He wears a brown or dark winter coat, a thick scarf wrapped around his neck and a large fur ushanka hat framing his face; his expression is calm and direct as he looks straight into the camera.
Lighting: deep night lighting, as dark as a typical Russian courtyard around 10 p.m. in winter. The scene is illuminated mainly by one or two distant streetlamps and the scattered warm glows from a few apartment windows, creating strong contrast between small pools of warm light and large areas of cold blue-black shadow. His face is lit by a soft but dim streetlamp from the side or slightly above, giving gentle highlights on the eyes, nose and lips, with pronounced soft shadows under the hat and along the scarf, while the snow around him falls into a cool, bluish darkness. Style: low-key cinematic winter portrait in 4K, with rich deep blues, desaturated browns and warm orange points of light from the windows, subtle film grain and slightly blurred, glowing streetlights in the background. Camera language: static frontal medium-close shot (head and shoulders to mid-chest), shot on a professional full-frame camera with a 50–85 mm lens and shallow depth of field, man in crisp focus despite the low light, background apartment block and courtyard melting into dark, soft bokeh. Mood and atmosphere: quiet, lonely Russian winter night in a residential district, a mix of cold, silence and introspection, with his clearly readable face emerging from the surrounding darkness. Preserve the man’s face, proportions, facial expression and all appearance details from the attached photo as accurately as possible, with no distortion."""
            },

            "books": {
                "title": "Книги",
                "prompt": """Young man from the attached photo lying on his back in fresh white snow, captured in a cinematic medium-close shot from slightly above. He is positioned in the lower part of the frame, head tilted back, looking up toward the sky or slightly to the side. He wears a black coat that is open at the collar, revealing a bare neckline with no necklace or choker, his skin softly lit and clearly visible. In the upper part of the frame, very close to his head, a pile of books is burning intensely on the snow: bright orange flames, blackened pages curling, charred paper, and partially readable covers lying directly on the snow, with small patches of soot and ash scattered around.
Style: moody, slightly vintage cinematic winter scene in 4K, with a strong contrast between the cold bluish snow and the warm orange-red fire, soft film-like grain and muted, slightly desaturated colors on the man’s clothing and skin. Lighting: overcast natural daylight or very soft diffuse light, with subtle cool tones on the snow and gentle warm reflections from the fire on his face, hair and coat, giving a faint golden rim along the edges nearest to the flames. Camera language: static overhead or slightly diagonal angle, medium to medium-close shot framing him from mid-torso up, shot on a professional full-frame camera with a 35–50 mm lens, moderate depth of field keeping both the man and the burning books in clear focus while the distant snow falls off into a soft blur. Mood and atmosphere: poetic, dramatic and slightly surreal, evoking themes of destruction and calm acceptance — a young man peacefully lying in the snow next to burning books, with a quiet, resigned or contemplative expression. Preserve the man’s face, proportions, hairstyle and all appearance details from the attached photo as accurately as possible, with no distortion."""
            },
        },

        "female": {
            "title": "Женские",

            "floor": {
                "title": "На полу",
                "prompt": """Young woman from the attached photo depicted lying on a dark party floor after a wild night, surrounded by a thick layer of bright metallic confetti, glitter and tinsel. She wears an elegant fitted black dress and neat black sunglasses, with a festive silver-gold tinsel garland casually draped around her neck and shoulders, a white party blower in her mouth, relaxed pose and a slightly bold, confident expression. In the upper part of the frame only the legs of party guests are visible: on the left a man in light grey dress trousers and polished black leather shoes, on the right a woman in a short black cocktail dress, sheer black tights and high-heel sandals, their legs framing the girl lying on the floor. Environment: dark club floor completely covered with gold, silver, blue, red, green and purple confetti pieces, shiny foil streamers and serpentine, with deep black drapery in the background, creating a chaotic nightclub afterparty mood. Photo-realistic, cinematic fashion editorial photograph in 4K, high contrast, strong specular highlights on the confetti and tinsel, deep shadows, luxurious glossy glamour. Lighting: warm directional studio light from above and slightly from the side, soft but defined shadows, highlights on skin, the black dress and party decorations, background fading into darkness. Camera language: high angle, almost top-down medium shot on a professional full-frame camera with a 50–85 mm lens, moderately shallow depth of field, crisp focus on the woman’s face and upper body, rich confetti texture across the whole frame. Mood and atmosphere: bold, ironic, glossy post-party glamour. Preserve the face, proportions and expression from the attached photo without distortion."""
            },

            "chair_mountain": {
                "title": "Стул на горе",
                "prompt": """Young woman from the attached photo sitting on a wooden chair in the middle of a sunny snowy mountain landscape. She wears a chunky knitted winter sweater with a Nordic pattern: red and white design across the chest and sleeves, red collar, red cuffs and hem, white sleeves and base, with a thin white layer of clothing visible at the neck. On the lower body she has black ski or trekking pants. She sits in a relaxed feminine pose, leaning back slightly against the chair, legs crossed one over the other, with her hands resting softly on her top knee or on the arm of the chair, fingers relaxed and graceful. The woman has the same facial features, hairstyle and overall appearance as in the attached photo, preserved accurately without distortion or stylization, with a calm, confident gaze directly into the camera. Background: bright open snowfield under clear daylight, with a large snow-covered mountain softly blurred behind her and a clean pale blue winter sky above. Style: photo-realistic, clean cinematic outdoor portrait in 4K, with a cool snowy color palette and warm skin and sweater tones, subtle backlight along the hair and shoulders. Lighting: bright daytime mountain sun, gentle natural shadows on the face, reflected light from the snow below creating even, flattering illumination on the skin and sweater texture. Camera language: static frontal or slightly low angle, medium to medium-close shot (from chest to knees), professional full-frame camera with a 50–85 mm lens, moderately shallow depth of field, sharp focus on the face and hands, mountains and snow in the background softly blurred. Mood and atmosphere: fresh winter day in the mountains, feeling of freedom, calm and cozy warmth thanks to the sweater. Preserve the face, proportions, facial expression and all appearance details from the attached photo as accurately as possible, with no distortion."""
            },

            "frozen_face": {
                "title": "Ебало замерзшее",
                "prompt": """Young woman from the attached photo shown in an extreme close-up winter portrait, her face filling the frame from mid-forehead to chin, directly facing the camera. Only her face is visible, tightly framed by a fur-lined hood and thick frost. Her skin has a cold rosy tone, long dark eyelashes and well-defined eyebrows, with subtle freckles visible on her cheeks and nose. Her nose, cheeks and the area around her mouth are covered in dense frost and tiny ice crystals, as if she has been walking in severe sub-zero temperatures; a thin layer of frost also sits on her natural soft pink lips. Around her face the fur trim of the hood and the high winter collar are heavily coated with snow and rime, with a few frozen strands of hair peeking out, also covered in ice. The background is softly blurred and indistinct, in cold blue tones, so all attention is drawn to her eyes. Style: hyper-realistic cinematic winter portrait in 4K, with micro-details in the skin, frost and fur, a cool blue-cyan color palette contrasted by gentle warm pinks in the lips and cheeks. Lighting: soft diffused northern daylight, like an overcast snowy day, with no harsh shadows, evenly illuminating the face and emphasizing the depth of her eyes and the texture of the frost, slightly cool in tone. Camera language: static frontal extreme close-up shot with an 85–100 mm lens and very shallow depth of field, razor-sharp focus on the eyes and center of the face, fur and background gently blurred. Mood and atmosphere: intense arctic cold, quiet, resilience and inner calm, her gaze steady, focused and slightly contemplative. Preserve the face, proportions, gaze and all appearance details from the attached photo as accurately as possible, with no distortion."""
            },

            "soviet": {
                "title": "Совок",
                "prompt": """Young woman from the attached photo standing outdoors in a snowy courtyard in front of a Soviet-era apartment block, captured in a closer portrait framing. The camera is focused tightly on her from mid-chest upward, so her face and features are clearly visible and sharp, while the background buildings, trees, streetlights and basketball hoop are softly blurred. She wears a brown winter coat, a thick beige scarf wrapped around her neck and a large fur ushanka hat framing her face; her expression is calm and direct as she looks straight into the camera.
Lighting: deep night lighting, as dark as a typical Russian courtyard around 10 p.m. in winter. The scene is illuminated mainly by one or two distant streetlamps and the scattered warm glows from a few apartment windows, creating strong contrast between small pools of warm light and large areas of cold blue-black shadow. Her face is lit by a soft but dim streetlamp from the side or slightly above, giving gentle highlights on the eyes, nose and lips, with pronounced soft shadows under the hat and along the scarf, while the snow around her falls into a cool, bluish darkness. Style: low-key cinematic winter portrait in 4K, with rich deep blues, desaturated browns and warm orange points of light from the windows, subtle film grain and slightly blurred, glowing streetlights in the background. Camera language: static frontal medium-close shot (head and shoulders to mid-chest), shot on a professional full-frame camera with a 50–85 mm lens and shallow depth of field, woman in crisp focus despite the low light, background apartment block and courtyard melting into dark, soft bokeh. Mood and atmosphere: quiet, lonely Russian winter night in a residential district, a mix of cold, silence and introspection, with her clearly readable face emerging from the surrounding darkness. Preserve the woman’s face, proportions, facial expression and all appearance details from the attached photo as accurately as possible, with no distortion"""
            },

            "books": {
                "title": "Книги",
                "prompt": """Young woman from the attached photo lying on her back in fresh white snow, captured in a cinematic medium-close shot from slightly above. She is positioned in the lower part of the frame, head tilted back, looking up toward the sky or slightly to the side. She wears a dark green or deep teal coat that is open at the collar, revealing a bare neckline with a delicate white pearl or beaded choker around her throat, skin softly lit and clearly visible. In the upper part of the frame, very close to her head, a pile of books is burning intensely on the snow: bright orange flames, blackened pages curling, charred paper, and partially readable covers lying directly on the snow, with small patches of soot and ash scattered around.
Style: moody, slightly vintage cinematic winter scene in 4K, with a strong contrast between the cold bluish snow and the warm orange-red fire, soft film-like grain and muted, slightly desaturated colors on the woman’s clothing and skin. Lighting: overcast natural daylight or very soft diffuse light, with subtle cool tones on the snow and gentle warm reflections from the fire on her face, hair and coat, giving a faint golden rim along the edges nearest to the flames. Camera language: static overhead or slightly diagonal angle, medium to medium-close shot framing her from mid-torso up, shot on a professional full-frame camera with a 35–50 mm lens, moderate depth of field keeping both the woman and the burning books in clear focus while the distant snow falls off into a soft blur. Mood and atmosphere: poetic, dramatic and slightly surreal, evoking themes of destruction and calm acceptance — a young woman peacefully lying in the snow next to burning books, with a quiet, resigned or contemplative expression. Preserve the woman’s face, proportions, hairstyle and all appearance details from the attached photo as accurately as possible, with no distortion."""
            },
        },
    },

    "style": {
        "title": "Стиль",

        "male": {
            "title": "Мужские",

            "punch": {
                "title": "Кулак",
                "prompt": """Young man from the attached photo in a playful black-and-white studio portrait, shot against a clean white background. He is framed from the chest up, facing the camera directly, wearing a classic black suit, white dress shirt and narrow black tie, styled like a sharp formal portrait. A large boxing glove is captured just as it is about to hit, or has only barely touched, the left side of his face: it presses very slightly into his cheek, creating only a small, subtle distortion of the skin, while the overall facial structure remains clearly recognizable. One eye is just beginning to squint and the mouth is only slightly pulled to the side in a hint of a grimace, as if the impact will happen fully a fraction of a second later.
Style: high-contrast monochrome fashion/editorial image in 4K, with deep blacks in the suit and glove, bright whites in the shirt and background, and crisp mid-tones on the skin. Lighting: strong direct flash from the front, creating hard shadows and a very clean, graphic look, with sharp detail in facial texture and the glove’s surface. Camera language: static frontal medium-close shot on a 50–85 mm lens, shallow to medium depth of field keeping the man and glove perfectly sharp while the white background remains smooth and featureless. Mood and atmosphere: humorous, edgy and slightly absurd, like a fashion campaign image frozen a split second before a full punch. Preserve the man’s face, proportions, hairstyle and all appearance details from the attached photo as accurately as possible, with only minimal, localized deformation where the glove touches the cheek."""
            },

            "hairstyles": {
                "title": "Прически",
                "prompt": """Transform the attached male portrait photo into a 3×3 grid of professional studio-quality images of the SAME man. Keep his face, proportions, skin tone and overall appearance identical to the uploaded photo in all 9 tiles, only change the hairstyle in each image. Neutral light grey studio background, straight-on camera angle, head-and-shoulders framing, soft even beauty lighting, sharp focus, natural retouch, photorealistic, 4K.
Generate 9 clearly different, realistic male hairstyles: short fade, buzz cut, classic side part, slick back, messy textured crop, medium wavy hair, curly top with fade, longer layered hairstyle to the shoulders, and a man bun. Arrange all variations in a clean 3×3 grid within one image, equal spacing, consistent colors and exposure across the grid."""
            },

            "finger_glasses": {
                "title": "Палец очки",
                "prompt": """Man from attached photo in an extreme close-up portrait shot from a high angle. He is wearing oversized white retro-futuristic sunglasses. Facial expression is intense and expressive: wide grin showing teeth, head tilted back, finger pulling the corner of the mouth or touching the cheek. Black and white photography, high contrast, sharp focus on skin texture, teeth, and glasses. Edgy fashion editorial style, dynamic and slightly crazy emotion. Flash photography aesthetic with harsh shadows. Preserve facial features and identity (adapted to expression). 4K."""
            },

            "rooftop": {
                "title": "На крыше",
                "prompt": """Man from attached photo standing on a rooftop balcony with city buildings in the background. Shot with an extreme fisheye lens (8mm), creating a strong spherical distortion effect with circular black vignetting edges. He is leaning slightly towards the camera, looking cool and relaxed. Wearing a retro 1960s striped blazer, button-up shirt, and trousers. Black and white film photography, high contrast, grainy texture. British rock star aesthetic, mod style. Sky with dramatic clouds above. Preserve facial features and identity from photo (adapted to fisheye distortion). 4K."""
            },

            "punk": {
                "title": "Панк",
                "prompt": """Young man from the attached photo in a bold studio portrait with a clean gradient background shifting from teal at the bottom to darker blue at the top. He is centered in the frame, captured from chest up, facing the camera directly with a playful, rebellious expression, tongue slightly sticking out. He has spiky, brightly dyed red-orange hair styled into multiple sharp spikes radiating outward, matching his glossy red rectangular sunglasses. He wears a black sporty sweatshirt with thin, bright orange piping lines along the shoulders and sleeves, plus small hoop earrings in both ears.
Style: vibrant, modern studio fashion portrait in 4K, hyper-realistic with smooth but detailed skin texture and crisp hair strands. Lighting: soft but punchy three-point studio lighting with a subtle rim light separating him from the background and gentle reflections in the sunglasses, minimal shadows on the face for a clean look. Camera language: static frontal medium-close shot, shot on a professional full-frame camera with a 50–85 mm lens, shallow depth of field keeping the subject tack-sharp while the gradient background stays smoothly blurred. Mood and atmosphere: energetic, fun and slightly punk, emphasizing color contrast between the red hair and glasses, the black outfit and the cool blue background. Preserve the man’s face, proportions, hairstyle, accessories and all appearance details from the attached photo as accurately as possible, with no distortion."""
            },
        },

        "female": {
            "title": "Женские",

            "punch": {
                "title": "Кулак",
                "prompt": """oung woman from the attached photo in a playful black-and-white studio portrait, shot against a clean white background. She is framed from the chest up, facing the camera directly, wearing a classic black suit, white dress shirt and narrow black tie, styled like a sharp formal portrait. A large boxing glove is captured just as it is about to hit, or has only barely touched, the left side of her face: it presses very slightly into her cheek, creating only a small, subtle distortion of the skin, while the overall facial structure remains clearly recognizable. One eye is just beginning to squint and the mouth is only slightly pulled to the side in a hint of a grimace, as if the impact will happen fully a fraction of a second later.
Style: high-contrast monochrome fashion/editorial image in 4K, with deep blacks in the suit and glove, bright whites in the shirt and background, and crisp mid-tones on the skin. Lighting: strong direct flash from the front, creating hard shadows and a very clean, graphic look, with sharp detail in facial texture and the glove’s surface. Camera language: static frontal medium-close shot on a 50–85 mm lens, shallow to medium depth of field keeping the man and glove perfectly sharp while the white background remains smooth and featureless. Mood and atmosphere: humorous, edgy and slightly absurd, like a fashion campaign image frozen a split second before a full punch. Preserve the man’s face, proportions, hairstyle and all appearance details from the attached photo as accurately as possible, with only minimal, localized deformation where the glove touches the cheek."""
            },

            "hairstyles": {
                "title": "Прически",
                "prompt": """Transform the attached female portrait photo into a 3×3 grid of professional studio-quality images of the SAME woman. Keep her face, proportions, skin tone and overall appearance identical to the uploaded photo in all 9 tiles, only change the hairstyle in each image. Neutral light grey studio background, straight-on camera angle, head-and-shoulders framing, soft even beauty lighting, sharp focus, natural retouch, photorealistic, 4K.
Generate 9 clearly different, realistic female hairstyles: sleek straight bob, wavy long hair, high ponytail, messy bun, classic pixie cut, shoulder-length layered hair with side-swept bangs, curly afro, half-up half-down waves, and retro 70s feathered hairstyle. Arrange all variations in a clean 3×3 grid within one image, equal spacing, consistent colors and exposure across the grid."""
            },

            "finger_glasses": {
                "title": "Палец очки",
                "prompt": """Young woman from the attached photo in an extreme close-up portrait shot from a high angle. She is wearing oversized white retro-futuristic sunglasses that dominate the upper part of her face. Facial expression is intense and expressive: a wide grin showing her teeth, head tilted back toward the camera, with one finger pulling gently at the corner of her mouth or touching her cheek, creating a playful, slightly crazy emotion.
Black and white photography, high contrast, with sharp focus on skin texture, lips, teeth and the glossy surface of the glasses, background falling into soft darkness. Edgy fashion editorial style, bold and dynamic, with a sense of wild energy and attitude. Flash photography aesthetic with hard, direct light from the front or slightly above, producing crisp shadows around the nose, chin and hand. Preserve the woman’s facial features, proportions and identity from the attached photo, only adapting them naturally to this exaggerated expression. 4K resolution."""
            },

            "rooftop": {
                "title": "На крыше",
                "prompt": """Young woman from the attached photo standing on a rooftop balcony with city buildings in the background. Shot with an extreme fisheye lens (8 mm), creating a strong spherical distortion effect with circular black vignetting around the frame, but her face remains clearly recognizable. She is leaning slightly toward the camera, looking cool, confident and relaxed. She wears a feminine retro 1960s outfit: a fitted striped blazer over a light blouse, a short A-line skirt, sheer tights and stylish low-heel shoes, optionally with subtle jewelry such as small earrings or a thin bracelet.
Black and white film photography, high contrast with deep blacks and bright highlights, visible grainy texture across the image. Overall vibe: British rock-star mod aesthetic, but with a chic feminine twist. Dramatic cloudy sky curves overhead due to the fisheye effect, while the city skyline and balcony rail distort in a circular way around her. Preserve the woman’s facial features, proportions and identity from the attached photo, only adapting them naturally to the fisheye distortion. 4K resolution, sharp focus on her face and upper body, slightly softer background."""
            },

            "punk": {
                "title": "Панк",
                "prompt": """Young woman from the attached photo in a bold studio portrait with a clean gradient background shifting from teal at the bottom to darker blue at the top. She is centered in the frame, captured from chest up, facing the camera directly with a playful, rebellious expression, tongue slightly sticking out. She has spiky, brightly dyed red-orange hair styled into multiple sharp spikes radiating outward, matching her glossy red rectangular sunglasses. She wears a fitted black sporty top or sweatshirt with thin, bright orange piping lines along the shoulders and sleeves, plus small hoop earrings in both ears or other minimal feminine jewelry.
Style: vibrant, modern studio fashion portrait in 4K, hyper-realistic with smooth but detailed skin texture and crisp individual hair strands. Lighting: soft but punchy three-point studio lighting with a subtle rim light separating her from the background and gentle reflections in the sunglasses, minimal shadows on the face for a clean, polished look. Camera language: static frontal medium-close shot, shot on a professional full-frame camera with a 50–85 mm lens, shallow depth of field keeping the subject tack-sharp while the gradient background stays smoothly blurred. Mood and atmosphere: energetic, fun and slightly punk, emphasizing the color contrast between the red hair and glasses, the black outfit and the cool blue background. Preserve the woman’s face, proportions, hairstyle, accessories and all appearance details from the attached photo as accurately as possible, with no distortion."""
            },
        },
    },

    "travel": {
        "title": "Путешествие",

        "male": {
            "title": "Мужские",

            "mountains": {
                "title": "Горы",
                "prompt": """Young man from the attached photo standing on a snowy mountain slope, captured in a tighter portrait-style framing to preserve facial detail. He is shown from mid-chest up, centered in the frame, arms confidently crossed over his chest, looking slightly toward the camera with a relaxed, self-assured expression. He wears a bright orange puffer jacket with the hood down and reflective sunglasses, with cool blue-white alpine peaks filling the softly blurred background.
Style: ultra-realistic outdoor portrait in 4K, with crisp detail on his face, hair, jacket fabric and glasses, while the mountains behind are slightly out of focus to emphasize his identity. Lighting: bright midday mountain sun with clear, cool daylight; natural contrast, soft blue shadows on the snow, subtle highlights on the jacket and frames. Camera language: static frontal medium-close shot at eye level, shot on a professional full-frame camera with a 50–85 mm lens and shallow depth of field, sharp focus on the man’s face and upper body, background mountains gently blurred. Mood and atmosphere: confident, fresh, adventurous, like a hero shot from a winter hiking or ski campaign. Preserve the man’s face, proportions, hairstyle, sunglasses and all appearance details from the attached photo as accurately as possible, with no distortion."""
            },

            "boat": {
                "title": "На лодке",
                "prompt": """Young man from the attached photo relaxing on a boat at golden hour, captured in a horizontal medium shot from mid-thigh up. He is seated sideways on a light-colored boat bench, one arm comfortably draped along the backrest, the other hand holding a brown glass beer bottle to his lips as he takes a sip, looking toward the sunlit coastline. He wears dark sunglasses, a loose open navy linen shirt with a few buttons undone, showing a silver chain necklace, and light shorts; tattoos on his forearm and a bracelet catch the warm light.
In the background, a picturesque Mediterranean seaside town climbs up the hillside: pastel houses, stone walls, a marina with sailboats, and an old fortress or castle crowning the top of the hill, all bathed in soft golden sunlight. The sea around the boat is deep blue with gentle ripples reflecting the sky and warm highlights. Style: ultra-realistic vacation lifestyle photograph in 4K, rich warm color grading with strong sunset tones on skin and buildings, natural contrast and subtle film-like texture. Lighting: low golden-hour sun from the side, casting soft shadows and a warm glow on his face, shirt and bottle, with slight specular reflections on the water. Camera language: static eye-level medium shot on a 35–50 mm lens, shallow to medium depth of field keeping the man and the boat bench sharply in focus while the town and castle behind are slightly softened but still recognizable. Mood and atmosphere: relaxed, luxurious summer evening on the coast, a candid moment of effortless enjoyment. Preserve the man’s face, proportions, hairstyle, sunglasses, tattoos and all appearance details from the attached photo as accurately as possible, with no distortion."""
            },

            "japan": {
                "title": "Япония",
                "prompt": """Young man from the attached photo standing confidently in the middle of a vibrant city street at dusk, directly in front of a classic red taxi. He is framed in a full-body shot, leaning lightly against the front bumper with legs relaxed, looking straight at the camera with a calm, cool expression. He wears dark sunglasses, a clean white T-shirt tucked into high-waisted light blue jeans with a black belt, a slim watch on left wrist, and is tying or adjusting a dark bandana or scarf around his neck with both hands near his collar.
Behind him, the street recedes into depth, lined with tall buildings covered in glowing neon signs and vertical banners with East Asian characters, car headlights and shop lights creating bokeh and reflections on the taxi’s glossy red paint. Style: ultra-realistic urban street-fashion portrait in 4K, with crisp detail in clothing, car and signage, slightly saturated colors and a subtle cinematic grade. Lighting: soft, overcast evening light mixed with warm neon and streetlamp accents, giving gentle, even illumination on his face and outfit while the background signs and cars glow more intensely. Camera language: static frontal shot at eye level on a 35–50 mm lens, medium depth of field keeping the man and taxi very sharp while the deeper city background gradually softens. Mood and atmosphere: stylish, cinematic “cool guy in the city” vibe, like a frame from a modern streetwear campaign. Preserve the man’s face, proportions, hairstyle, sunglasses and all appearance details from the attached photo as accurately as possible, with no distortion."""
            },

            "cafe": {
                "title": "Кафе",
                "prompt": """Young man from the attached photo sitting at a Parisian sidewalk café during golden hour, captured in a relaxed medium shot from the waist up. He is seated on a classic woven bistro chair, one leg casually crossed over the other, leaning slightly toward the camera. He wears dark sunglasses, a light beige button-up shirt with the sleeves rolled to the forearms, a patterned silk neckerchief tied loosely around his neck, tailored beige trousers, a wristwatch and simple bracelet, giving him a refined yet casual look.
Behind him, elegant Haussmann-style buildings stretch down the street, their façades glowing warm in the low evening sun. Green shrubs, café tables with white tops, and red bistro chairs frame the foreground, while cars and pedestrians are softly visible in the background, reinforcing the Paris street atmosphere. Style: ultra-realistic lifestyle portrait in 4K, with warm sunset color grading, gentle contrast and subtle film-like texture. Lighting: golden-hour sunlight from the side, casting soft, flattering shadows on his face and clothes, with warm highlights along the edges and gentle reflections in the sunglasses. Camera language: static frontal medium shot at eye level on a 35–50 mm lens, shallow to medium depth of field keeping the man sharp while the street and buildings fall into a soft, creamy blur. Mood and atmosphere: relaxed, sophisticated European café moment, like a frame from a travel or fashion editorial. Preserve the man’s face, proportions, hairstyle, sunglasses and all appearance details from the attached photo as accurately as possible, with no distortion."""
            },

            "rocks": {
                "title": "Скалы",
                "prompt": """Young man standing among large rocks on a sunlit beach, captured in a relaxed fashion-editorial pose. He leans his back and hip lightly against a rock with his shoulders relaxed, both hands tucked into the pockets of his loose white trousers, while he looks directly into the camera with a calm, confident expression so his facial features are clearly readable. He wears an oversized white linen button-up shirt left casually open at the bottom to reveal a hint of torso, matching wide-leg white linen pants, and his hair is styled in slightly messy natural waves pushed back by the sea breeze.
Behind him, the ocean stretches to the horizon, sparkling in bright daylight with soft waves and scattered highlights on the water’s surface. The palette is warm and airy: pale sand, sunlit beige-gray rocks, soft turquoise and blue sea, and a clear, slightly hazy sky. Style: ultra-realistic lifestyle fashion photograph in 4K, with gentle film-like grain, soft contrast and natural skin texture. Lighting: bright midday coastal sun diffused by light haze, creating soft shadows and a warm glow on his face, hair and clothes, with subtle reflected light from the rocks. Camera language: vertical medium-full shot framed from head to mid-thigh, slightly low angle on a 50 mm lens, shallow to medium depth of field keeping the man and foreground rocks crisp while the sea and horizon fall into a gentle blur. Mood and atmosphere: effortless, breezy, minimalist beach elegance, like a campaign image for a men’s summer linen collection. Preserve the man’s face, proportions, hairstyle and all appearance details from the reference face as accurately as possible, with no distortion."""
            },
        },

        "female": {
            "title": "Женские",

            "mountains": {
                "title": "Горы",
                "prompt": """Young woman from the attached photo standing on a snowy mountain slope, captured in a tighter portrait-style framing to preserve facial detail. She is shown from mid-chest up, centered in the frame, arms confidently crossed over her chest, looking slightly toward the camera with a calm, self-assured expression. She wears a bright orange puffer jacket with the hood down and modern sunglasses that catch the light, giving her a stylish, sporty appearance, while soft, blue-white alpine peaks fill the slightly blurred background.
Style: ultra-realistic outdoor adventure portrait in 4K, with very high detail in fabric, hair, skin and glasses, while the mountains are gently out of focus to emphasize her identity. Lighting: bright midday mountain sun with clear, cool daylight, strong but natural contrast, subtle rim light along the jacket and hair, soft blue shadows on the snow. Camera language: static frontal medium-close shot at eye level, shot on a professional full-frame camera with a 50–85 mm lens and shallow depth of field, sharp focus on the woman’s face and upper body, background mountains softly blurred. Mood and atmosphere: confident, fresh and adventurous, like a hero frame from a lifestyle campaign for women’s winter travel or technical outerwear. Preserve the woman’s face, proportions, hairstyle and all appearance details from the reference face as accurately as possible, with no distortion."""
            },

            "boat": {
                "title": "На лодке",
                "prompt": """Young woman from the attached photo relaxing on a boat at golden hour, captured in a horizontal medium shot from mid-thigh up. She is seated sideways on a light-colored boat bench, one arm comfortably draped along the backrest, the other hand holding a brown glass beer or soda bottle to her lips as she takes a sip, looking toward the sunlit coastline with a calm, satisfied expression. She wears dark sunglasses, a loose, slightly oversized navy linen blouse or lightweight shirt with a few buttons undone, a delicate silver necklace, and high-waisted light shorts or a soft summer skirt; her arms and legs are bare, with smooth skin and no tattoos.
In the background, a picturesque Mediterranean seaside town climbs up the hillside: pastel houses, stone walls, a marina with sailboats, and an old fortress or castle crowning the top of the hill, all bathed in soft golden sunlight. The sea around the boat is deep blue with gentle ripples reflecting the sky and warm highlights. Style: ultra-realistic vacation lifestyle photograph in 4K, rich warm color grading with strong sunset tones on skin and buildings, natural contrast and subtle film-like texture. Lighting: low golden-hour sun from the side, casting soft shadows and a warm glow on her face, hair, blouse and bottle, with slight specular reflections on the water. Camera language: static eye-level medium shot on a 35–50 mm lens, shallow to medium depth of field keeping the woman and the boat bench sharply in focus while the town and castle behind are slightly softened but still recognizable. Mood and atmosphere: relaxed, feminine, luxurious summer evening on the coast, a candid moment of effortless enjoyment. Preserve the woman’s face, proportions, hairstyle and all appearance details from the reference face as accurately as possible, with no distortion."""
            },

            "japan": {
                "title": "Япония",
                "prompt": """Young woman from the attached photo standing confidently in the middle of a vibrant city street at dusk, directly in front of a classic red taxi. She is framed in a full-body shot, leaning lightly against the front bumper with one leg relaxed and crossed slightly in front of the other, looking straight at the camera. She wears dark sunglasses, a fitted white short-sleeve top tucked into high-waisted light blue jeans with a black belt, a slim watch or bracelet on one wrist, and is tying or adjusting a dark silk neck scarf with both hands near her collar, adding a chic, vintage touch.
Behind her, the street recedes into depth, lined with tall buildings covered in glowing neon signs and vertical banners with East Asian characters, car headlights and shop lights creating bokeh and reflections on the taxi’s glossy red paint. Style: ultra-realistic urban street-fashion portrait in 4K, with crisp detail in clothing, car and signage, slightly saturated colors and a subtle cinematic grade. Lighting: soft, overcast evening light mixed with warm neon and streetlamp accents, giving gentle, even illumination on her face and outfit while the background signs and cars glow more intensely. Camera language: static frontal shot at eye level on a 35–50 mm lens, medium depth of field keeping the woman and taxi very sharp while the deeper city background gradually softens. Mood and atmosphere: stylish, feminine, cinematic city-night vibe, like a frame from a modern streetwear or travel campaign. Preserve the woman’s face, proportions, hairstyle, sunglasses and all appearance details from the reference face as accurately as possible, with no distortion."""
            },

            "cafe": {
                "title": "Кафе",
                "prompt": """Young woman from the attached photo sitting at a Parisian sidewalk café during golden hour, captured in a relaxed medium shot from the waist up. She is seated on a classic woven bistro chair, one leg casually crossed over the other, leaning slightly toward the camera with a soft, confident smile, looking directly into the lens so her facial features are clearly visible. She wears dark sunglasses, a light beige or cream button-up blouse with the sleeves rolled to the forearms, a patterned silk neck scarf tied loosely around her neck, tailored high-waisted beige trousers or a chic skirt, and a delicate wristwatch and bracelet, giving her a refined yet feminine look.
Behind her, elegant Haussmann-style Parisian buildings stretch down the street, their façades glowing warm in the low evening sun. Green shrubs, café tables with white tops and red bistro chairs frame the foreground, while cars and pedestrians are softly visible in the background, reinforcing the lively city atmosphere. Style: ultra-realistic lifestyle portrait in 4K, with warm sunset color grading, gentle contrast and subtle film-like texture. Lighting: golden-hour sunlight from the side, casting soft, flattering shadows on her face and clothes, with warm highlights along the edges and gentle reflections in the sunglasses. Camera language: static frontal medium shot at eye level on a 35–50 mm lens, shallow to medium depth of field keeping the woman sharp while the street and buildings fall into a soft, creamy blur. Mood and atmosphere: relaxed, elegant European café moment, like a frame from a modern travel or fashion editorial. Preserve the woman’s face, proportions, hairstyle, sunglasses and all appearance details from the reference face as accurately as possible, with no distortion."""
            },

            "rocks": {
                "title": "Скалы",
                "prompt": """Young woman standing among large rocks on a sunlit beach, captured in a relaxed fashion-editorial pose. She leans her back and hip lightly against a rock, one hand tucked into the pocket of her loose white trousers, the other resting on top of her head, elbow bent, while she looks directly into the camera with a calm, confident expression. She wears an oversized white linen button-up shirt left casually open at the bottom to reveal a hint of midriff, matching wide-leg white linen pants, and her hair is styled in slightly messy natural waves or curls swept back by the sea breeze.
Behind her, the ocean stretches to the horizon, sparkling in the bright daylight with soft waves and scattered highlights on the water’s surface. The color palette is warm and airy: pale sand, sunlit rocks in beige and gray tones, soft turquoise and blue sea, and a clear, slightly hazy sky. Style: ultra-realistic lifestyle fashion photograph in 4K, with gentle film-like grain, soft contrast and natural skin texture. Lighting: bright midday coastal sun diffused by light haze, creating soft shadows and warm glow on her face and clothes, subtle reflected light from the rocks. Camera language: vertical medium-full shot framed from head to mid-thigh, slightly low angle on a 50 mm lens, shallow to medium depth of field keeping the woman and foreground rocks sharp while the sea and horizon fall into a gentle blur. Mood and atmosphere: effortless, breezy, minimalist beach elegance, like a lookbook shot for a summer linen collection. Preserve the woman’s face, proportions, hairstyle and all appearance details from the reference face as accurately as possible, with no distortion."""
            },
        },
    },

}
