"""add users webinars and webinar_registrations

Revision ID: 26a0d1c7181d
Revises: 
Create Date: 2025-12-18 22:30:27.853520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26a0d1c7181d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('tg_id', sa.BIGINT(), nullable=False),
                    sa.Column('username', sa.String(length=64), nullable=True),
                    sa.Column('first_name', sa.String(length=128), nullable=True),
                    sa.Column('last_name', sa.String(length=128), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
                    sa.Column('is_blocked', sa.Boolean(), server_default='false', nullable=False),
                    sa.Column('welcome_photo_generated', sa.Boolean(), server_default='false', nullable=False),
                    sa.Column('subbscribed_photo_generated', sa.Boolean(), server_default='false', nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('tg_id')
                    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('webinars',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=False),
                    sa.Column('description_small', sa.String(length=1024), nullable=False),
                    sa.Column('description_full', sa.Text(), nullable=False),
                    sa.Column('date_stream', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
                    sa.Column('is_free', sa.Boolean(), server_default='true', nullable=False),
                    sa.Column('price', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_webinars_id'), 'webinars', ['id'], unique=False)
    op.create_table(
        'webinar_registrations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('webinar_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.Enum('registered', 'cancelled', 'attended', 'no_show', name='webinar_registration_status'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['webinar_id'], ['webinars.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'webinar_id', name='uq_reg_user_webinar'),
    )
    op.create_index('ix_reg_status', 'webinar_registrations', ['status'], unique=False)
    op.create_index('ix_reg_user_id', 'webinar_registrations', ['user_id'], unique=False)
    op.create_index('ix_reg_webinar_id', 'webinar_registrations', ['webinar_id'], unique=False)
    op.create_index(op.f('ix_webinar_registrations_id'), 'webinar_registrations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webinar_registrations_id'), table_name='webinar_registrations')
    op.drop_index('ix_reg_webinar_id', table_name='webinar_registrations')
    op.drop_index('ix_reg_user_id', table_name='webinar_registrations')
    op.drop_index('ix_reg_status', table_name='webinar_registrations')
    op.drop_table('webinar_registrations')
    op.drop_index(op.f('ix_webinars_id'), table_name='webinars')
    op.drop_table('webinars')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.execute("DROP TYPE IF EXISTS webinar_registration_status")
    # ### end Alembic commands ###
